### PR TITLE
Changes to index.html

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Added missing `</p>` tag.
Added meta charset for proper names display.
Made the code clean and tidy.

### CODE REVIEW

**Comment by shyam2tayal** [comment]
sorry but same thing was done by other guy !! so can't merge yours but thanks for your effort!!

**Comment by r0hit-gupta** [comment]
There is still a missing `</p>` tag on line `49` of index.html

**Comment by shyam2tayal** [comment]
I do it anyway due to your efforts thanks a lot!!

**Comment by r0hit-gupta** [comment]
Thanks!

**Pull request merged**
